default:
  image: node:20.11.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/
    - client/node_modules/

stages:
  - deploy

deploy_server:
  stage: deploy
  script:
    - cd server
    - export VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_SERVER
    - npm ci
    - npm install --global vercel
    - vercel deploy --prod --token=$VERCEL_TOKEN
  only:
    - master

deploy_client:
  stage: deploy
  script:
    - cd client
    - export VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_CLIENT
    - npm ci
    - npm install --global vercel
    - vercel deploy --prod --token=$VERCEL_TOKEN
  only:
    - master

#preview_server:
#  stage: deploy
#  script:
#    - cd server
#    - export VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_SERVER
#    - npm ci
#    - npm install --global vercel@latest
#    - vercel deploy --token=$VERCEL_TOKEN
#  except:
#    - master
#
#preview_client:
#  stage: deploy
#  script:
#    - cd client
#    - export VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID_CLIENT
#    - npm ci
#    - npm install --global vercel
#    - vercel deploy --token=$VERCEL_TOKEN
#  except:
#    - master